### ISSUE TITLE
V 1.3 : Warning: Unexpected character in input

### ISSUE THREAD

**Issue by RomainDeschamps** [AXeL-dev/dolibarr-adminer-module#3]
![image](https://user-images.githubusercontent.com/11922840/89710438-5d734500-d983-11ea-9daa-5571018fd9b7.png)

Seems linked to 

![image](https://user-images.githubusercontent.com/11922840/89710456-83004e80-d983-11ea-8079-210396f8dfc8.png)

**Comment by AXeL-dev** [comment]
I think that the adminer file you updated was corrupted/buggy. So, anyway, i just re-updated it from the official website.

**Comment by RomainDeschamps** [comment]
Works fine now ! (Windows user... :-/)
