### ISSUE TITLE
Default permissions granted

### ISSUE THREAD

**Issue by RomainDeschamps** [AXeL-dev/dolibarr-adminer-module#4]
Default permission to ``use Adminer`` is granted. 
That means that any administrator can have access to the database when the module is enabled.

For security reasons, right to use adminer should be granted manually.

![image](https://user-images.githubusercontent.com/11922840/89710540-66b0e180-d984-11ea-8ded-9b816a90bfb2.png)

**Comment by AXeL-dev** [comment]
Re-enable module required to make changes effective.

**Comment by RomainDeschamps** [comment]
👍 

Remains : No translation of the perm label on the default permissions page

**Comment by AXeL-dev** [comment]
> Remains : No translation of the perm label on the default permissions page

Fixed (will be released later).
